name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Pull Docker image
      run: sudo docker pull fspanel:latest

    - name: Delete old Docker container
      run: |
        if [ "$(sudo docker ps -a -q -f name=container_fspanel)" ]; then
          sudo docker rm -f container_fspanel
        fi

    - name: Run Docker container
      run: sudo docker run -d -p ${{ secrets.SERVER_PORT }}:${{ secrets.SERVER_PORT }} --name container_fspanel fspanel:latest